# cd.yml
name: CD

on:
  push:
    branches:
      - prod

jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 1.22.5
      - name: Decrypt Android keys
        run: gpg --quiet --batch --yes --decrypt --passphrase="$ANDROID_KEYS_SECRET_PASSPHRASE" --output android/android_keys.zip android/android_keys.zip.gpg && cd android && jar xvf android_keys.zip && cd -
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Install Flutter dependencies
        run: flutter pub get
        # Add build runner commands here if you have any
      - name: Format files
        run: flutter format --line-length 100 --set-exit-if-changed .
      - name: Analyze files
        run: flutter analyze .
      # - name: Run the tests
      #   run: flutter test
      - name: Build the APK
        run: flutter build apk --release
      # - name: Create a Github Release APK
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: v0.0.1 # TODO change this to get the version from tags
      #     artifacts: "build/app/outputs/apk/release/app-release.apk"
      #     token: ${{ secrets.GITHUB_TOKEN }}

  # CD
  deploy_android:
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 1.22.5
      - name: Decrypt Android keys
        run: gpg --quiet --batch --yes --decrypt --passphrase="$ANDROID_KEYS_SECRET_PASSPHRASE" --output android/android_keys.zip android/android_keys.zip.gpg && cd android && jar xvf android_keys.zip && cd -
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build the App Bundle
        run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '>= 3.0.0'
      - name: Run Fastlane - closed_beta lane
        uses: maierj/fastlane-action@v2.0.0
        with:
          lane: closed_beta
          subdirectory: android
