name: CI - Push on prod branch

on:
  push:
    branches:
      - prod

jobs:
  build_android:
    name: Test and Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: 1.22.5
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter test
      - run: flutter build apk --release
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}